# This file stores configurations for your Shopify app.
client_id = "97fc241389cdb29af3e4b82071bcc8ae"
name = "Stocky Escape Kit"
application_url = "https://stocky-escape-kit.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,read_locations"

[auth]
redirect_urls = ["https://stocky-escape-kit.onrender.com/api/auth"]

[webhooks]
api_version = "2026-07"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Handled by: /app/routes/webhooks.app_purchases_one_time.update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app_purchases_one_time/update" ]
  uri = "/webhooks/app_purchases_one_time/update"

  # Mandatory compliance topic for public apps only
  # See: https://shopify.dev/docs/apps/build/privacy-law-compliance
  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]
